# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Onyx Renewable Partners
email: info@onyxrenewables.com
description: Investments in Sustainable Solutions
baseurl: "/onyx"
url: "https://dawaltconley.github.io"
twitter_username:
github_username:
collections:
    news:
        output: true
    careers:
        output: true
defaults:
  - scope:
        path: "_news"
    values:
        layout: "news"
        permalink: "/news/:year/:month/:day/:title"
  - scope:
        path: "_careers"
    values:
        layout: "job"
        permalink: "/careers/:title"

prose:
    ignore:
        - "_config.yml"
        - "_layouts"
        - "_sass"
        - "css"
        - "images"
        - "feed.xml"
        - "README.md"
        - ".gitignore"
    siteurl: "http://dawaltconley.github.io/onyx" # to be changed
    media: "images"
    metadata:
        _news:
            - name: "date"
              field:
                  element: "text"
                  label: "Date"
                  value: "CURRENT_DATETIME"
                  placeholder: "YYYY-MM-DD"
            - name: "about"
              field:
                  element: "multiselect"
                  label: "About"
                  help: >
                      Includes background info for a 
                      company mentioned in the article
                  options:
                      - name: "test 1"
                        value: "test 1"
                      - name: "test 2"
                        value: "test 2"
                  alterable: "true"
        _careers:
            - name: "date"
              field:
                  element: "text"
                  label: "Date"
                  value: "CURRENT_DATETIME"
                  placeholder: "YYYY-MM-DD"
            - name: "description"
              field:
                  element: "textarea"
                  label: "Job Description"
            - name: "responsibilities"
              field:
                  element: "textarea"
                  label: "Responsibilities"
                  help: "For a list, begin each new line with '- '"
                  placeholder: "- "
            - name: "reporting"
              field:
                  element: "textarea"
                  label: "Reporting"
                  placeholder: "- <br>- <br>- <br>- <br>- "
            - name: "qualifications"
              field:
                  element: "textarea"
                  label: "Minimum Qualifications"
                  placeholder: "- "
            - name: "conditions"
              field:
                  element: "textarea"
                  label: "Working Conditions"
                  help: >
                      ADA compliance and EEO statement 
                      will be automatically included.
                  placeholder: "- "

# Build settings
markdown: kramdown
