# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Onyx Renewable Partners
email: info@onyxrenewables.com
description: Investing in Sustainable Solutions
baseurl: "/onyx"
url: "https://dawaltconley.github.io"
logo: "/images/logos/onyx-logo-black-2.png"

permalink: /:title/
twitter_username:
github_username:
collections:
    news:
        output: true
    careers:
        output: true
    team:
        output: false
    partners:
        output: false
defaults:
  - scope:
        path: "_news"
    values:
        layout: "news"
        permalink: "/news/:year/:month/:day/:title"
  - scope:
        path: "_careers"
    values:
        layout: "job"
        permalink: "/careers/:title"

prose:
    ignore:
        - "_config.yml"
        - "_layouts"
        - "_sass"
        - "css"
        - "images"
        - "feed.xml"
        - "README.md"
        - ".gitignore"
    siteurl: "http://dawaltconley.github.io/onyx" # to be changed
    media: "images/headshots"
    metadata:
        _news:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
            - name: "date"
              field:
                  element: "text"
                  label: "Date"
                  value: "CURRENT_DATETIME"
                  placeholder: "YYYY-MM-DD"
            - name: "about"
              field:
                  element: "multiselect"
                  label: "About"
                  help: >
                      Includes background info for a 
                      company mentioned in the article
                  options: "http://dawaltconley.github.io/onyx/partners.jsonp"
                    # needs to be updated when site is moved
        _careers:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  placeholder: "Job Title"
            - name: "date"
              field:
                  element: "hidden"
                  value: "CURRENT_DATETIME"
            - name: "description"
              field:
                  element: "textarea"
                  label: "Job Description"
                  help: "All fields are optional."
            - name: "responsibilities"
              field:
                  element: "textarea"
                  label: "Responsibilities"
                  help: "For a list, begin each new line with '- '"
            - name: "reporting"
              field:
                  element: "textarea"
                  label: "Reporting"
            - name: "requirements"
              field:
                  element: "textarea"
                  label: "Minimum Requirements"
            - name: "preferred"
              field:
                  element: "textarea"
                  label: "Preferred Qualifications"
            - name: "conditions"
              field:
                  element: "textarea"
                  label: "Working Conditions"
            - name: "ada"
              field:
                  element: "checkbox"
                  label: "ADA Compliant"
                  help: >
                      EEO statement 
                      will be automatically included.
                  value: true
        _team:
            - name: "name"
              field:
                  element: "text"
                  label: "Name"
            - name: "job"
              field:
                  element: "text"
                  label: "Job Title"
        _partners:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
                  placeholder: "Partner Name"


# Build settings
markdown: kramdown
